name: Build App

on:
    push:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: SonarCloud Scan
          uses: sonarsource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            
            
          #setup-qemu action can be useful if you want to add emulation support with QEMU to be able to build against more platforms 
        - name: Set up QEMU 
          uses: docker/setup-qemu-action@v2
        
          #setup-buildx action will create and boot a builder using by default the docker-container builder driver. 
          #This is not required but recommended using it to be able to build multi-platform images, export cache, etc.
        - name: Set up Docker Buildx 
          uses: docker/setup-buildx-action@v2
          
          
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push
          uses: docker/build-push-action@v3
          with:
            push: true
            tags: user/app:latest
            tag_with_sha: true
            repository: kataaam/mywebserver
